import type { Metadata } from "next";
import { Lexend } from "next/font/google";
import "./globals.css";
import AppBar from "@/components/layout/app-bar";
import Script from "next/script";

const lexend = Lexend({
  subsets: ["latin"],
  variable: "--font-lexend",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Alo Avto",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <Script
          src="https://telegram.org/js/telegram-web-app.js"
          strategy="lazyOnload"
        />
      </head>
      <body
        suppressHydrationWarning
        className={`${lexend.variable} antialiased bg-blue-300 `}
      >
        {children}
        <AppBar />
      </body>
    </html>
  );
}
